- connect/src/com/telenor/connect/sms/SmsPinParseUtil.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- connect/src/com/telenor/connect/ui/Instruction.java
- connect/tests/src/test/java/com/telenor/connect/sms/HtmlToAndroidInstructionsInterfaceTest.java
- connect/tests/src/test/java/com/telenor/connect/sms/SmsPinParseUtilTest.java
Change pin reading algorithm to use regexes from Android instructions on page.
Pin's must still contain `CONNECT` in order to be evaluated.
> Change pin reading algorithm to use regexes

- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
On Android M, accepting sms permissions to autofill pin from already
received sms, after already receiving an sms, would trigger a race
condition. This commit fixes this.
> Fix reading of already received sms race condition

- connect-id-example/src/main/AndroidManifest.xml
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/WellKnownAPI.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- mobileconnect-example/src/main/AndroidManifest.xml
Add the possibility to execute request towards specific IPs found from
the .well-known configuration API using the cellular network interface, thus
achieving successful HE ,even when both WiFi and cellular are on.
For more information, see design doc at:
https://confluence.skunk-works.no/confluence/x/30BRAg.
> Forced HE over WiFi

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
1. Avoid forcing HE on a disconnected (stale) cellular network
2. Make the patch WiFi-independent, making it possible to force HE over the tethered connection other that WiFi (e.g. Bluetooth and USB)
> Extend Forced HE to support Bluetooth and USB

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
I haven't managed to recreate this error on my device, but we may have reasons
to merge this patch anyway.
My suspicion is, since client.warmup() is async, the client may not be always able
to create a new session if, for example, still "cold". I am not sure if this is exactly
the case here, but this patch can be safely merged even without being 100% sure.
The documentation states that client.newSession() may return null in case of errors
without being specific what kind of errors they might be. For that reason, it's sound
to check the session's validity prior to invoking its methods in any case.
If the not-null check introduced here fails for some reason, the only consequence would
be that we would have an Url that is not pre-optimized PRE_FETCH_URL. This would lead to
a performance that …
> Introduce session not-null check in ConnectLoginButton

- connect/src/com/telenor/connect/id/ConnectIdService.java
A possible pattern could be that they call ConnectSdk.logout() without previously
being logged in, possibly to make a fresh start or something. It is worth mentioning
that this pattern does not produce a crash in the app, just some annoying log entries
in it (and on the backend side as well).
Though this pattern looks like a misuse of the SDK, I think the SDK (and the backend
for that matter)  would benefit from not calling the revoke endpoint without tokens.
Otherwise, we might be snowed down with http 400 if many apps call
ConnectSdk.logout() unconditionally.
> Avoid requesting /oauth/revoke without tokens

- connect/src/com/telenor/connect/id/ConnectIdService.java
Fix the crash with crash dump:
Fatal Exception: java.lang.ClassCastException: java.lang.String cannot
be cast to java.util.Map
at
com.telenor.connect.ui.ConnectActivity.onError(ConnectActivity.java:100)
at
com.telenor.connect.id.ConnectIdService$1.failure(ConnectIdService.java:89)
at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5398)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
at …
> Fix ClassCastException crash

- connect/src/com/telenor/connect/AbstractSdkProfile.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/SdkProfile.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- connect/src/com/telenor/connect/utils/ConnectUtils.java
- connect/src/com/telenor/connect/utils/Validator.java
- connect/tests/src/test/java/com/telenor/connect/ui/ConnectWebViewClientTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ConnectUtilsTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ValidatorTest.java
We don't need it, since it is already contained within the Uri the ConnectActivity
has been started with. Besides, not having this variable will remove the problems
we might have if developers contrive to call ConnectSdk.authorize() multiple times.
Some of the crash reports indicate that they are doing exactly that.
> Scrap lastAuthState vairable

- connect/src/com/telenor/connect/id/ConnectIdService.java
Before this commit the updateTokens method would not notify on failure (call `ConnectUtils.sendTokenStateChanged(false);`), thus not calling `ConnectTokensStateTracker.onTokenStateChanged(boolean hasTokens)`.
> Fix updateTokens failure not notifying

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
Making the redirect target requirement more lenient by only comparing package names instead of comparing the full class names.
See issue #89.
> Redirect target requirement change

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
A setter lets you launch the custom tabs in the current Task instead of in a new Task. The custom tabs still launch in a new Task by default. See issue #91.
> Adding a setter for the custom tab in same/new task behavior

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/utils/CustomTabsHelper.java
Instead of always using Chrome custom tabs this change allows for using
the device default browser's custom tab, if one is available. This will give
a better chance of using SSO. E.g. Samsung Browser supports custom tabs.
Jira: CID-1802
> Use device default browser custom tab

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
LeakCanary reports a leak every time we use the ConnectLoginButton in our app:
> In se.telenor.mytelenor.alphatest:1.5.6.135.1:135.
> * com.telenor.app.mytelenor.ui.NewLoginActivity has leaked:
> * GC ROOT android.support.customtabs.CustomTabsClient$2.this$0 (anonymous subclass of android.support.customtabs.ICustomTabsCallback$Stub)
> * references android.support.customtabs.CustomTabsServiceConnection$1.this$0 (anonymous subclass of android.support.customtabs.CustomTabsClient)
> * references com.telenor.connect.ui.ConnectLoginButton$1.this$0 (anonymous subclass of android.support.customtabs.CustomTabsServiceConnection)
> * references com.telenor.connect.ui.ConnectLoginButton.mContext
> * leaks com.telenor.app.mytelenor.ui.NewLoginActivity instance
It looks like the anonymous subclass of …
> Fix ConnectLoginButton context leak

- connect-id-example/src/main/AndroidManifest.xml
- connect-id-example/src/main/java/com/telenor/connect/connectidexample/ExampleApplication.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/tests/src/test/java/com/telenor/connect/ConnectSdkTest.java
The `useStaging` boolean is read from the manifest and cannot be changed during runtime. This is a problem for us because we have to build two versions of our app when we do internal testing. Here is a suggestion for moving the staging configuration to the `sdkInitialize()` method instead, it would save us both time and confusion.
> Set useStaging in sdkInitialize

- connect-id-example/proguard-rules.pro
- connect/build.gradle
- connect/src/com/telenor/connect/AnalyticsAPI.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/WellKnownAPI.java
- connect/src/com/telenor/connect/id/ConnectAPI.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/utils/ConnectUrlHelper.java
- connect/src/com/telenor/connect/utils/HeadersDateUtil.java
- connect/src/com/telenor/connect/utils/RestHelper.java
- connect/tests/src/test/java/com/telenor/TestHelper.java
- connect/tests/src/test/java/com/telenor/connect/id/ConnectIdServiceTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/HeadersDateUtilTest.java
Hi, here's a suggestion for updating to Retrofit 2. See  #127
We're using Retrofit 2 in our app and it would be great if the Connect SDK uses the same.
The biggest change is that the Retrofit interfaces returns `Call<T>` objects and we now pass in callbacks to `call.enqueue()`. We also get error status codes in `onResponse` and have to check `response.isSuccessful()` there.
I've tried to keep the diff minimal, so I may not have formatted the code perfectly.
Example ProGuard rules are updated according to documentation for each library.
The WellKnownAPI mock methods in TestHelper are removed because they were unused and I don't know how to make them work with Retrofit 2.
I tested this with our app and it seems to work fine, but obviously it needs testing from you.
> Update to Retrofit 2

- connect/src/com/telenor/connect/id/ConnectIdService.java
When calling ConnectSdk.updateTokens(callback) it would correctly call
callback.noSignedInUser, but incorrectly continue execution (with an
empty refresh token). This commit fixes that.
> Fix updateTokens noSignedInUser bug

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ui/ConnectActivity.java
- connect/src/com/telenor/connect/ui/ConnectCustomTabLoginButton.java
Will now generate a new logSessionId on aborts, old sessions, and all
success scenarios (even when we fail to send analytics).
> Generate new logSessionId in more scenarios

- connect/src/com/telenor/connect/ConnectSdk.java
We get an activity leak when we login with ChromeCustomTab in SDK 1.9.5. Possibly related to #145 
> com.telenor.app.mytelenor.ui.LoginActivity has leaked:
> thread Thread.!(<Java Local>)! (named 'Answers Events Handler1')
> ↳ static ExecutorUtils$1$1.!($class$dexCache)!
> ↳ DexCache.!(runtimeInternalObjects)!
> ↳ array Object[].!([1376])!
> ↳ static ConnectSdk.!(smsBroadcastReceiver)!
> ↳ SmsBroadcastReceiver.!(smsHandler)!
> ↳ ConnectSdk$2.!(val$activity)! (anonymous implementation of com.telenor.connect.sms.SmsHandler)
> ↳ LoginActivity
It looks like smsBroadcastReceiver is only unregistered if an SMS is received?
https://github.com/telenordigital/connect-android-sdk/blob/master/connect/src/com/telenor/connect/ConnectSdk.java#L152-L165
I'm not sure it is the best solution but …
> Fix SmsBroadcastReceiver leaking activity

- connect/src/com/telenor/connect/ConnectSdk.java
Assuming that 
`getWellKnownConfig() == null || getWellKnownConfig().getAnalyticsEndpoint() == null`
doesn't mean that at next call some of them will not be null. 
Solution - write down values to local variables.
> Fix NPE in getAnalyticsEndpoint() handler

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
The issue can happen, when this part is called from a different thread,
however, it's hard to reproduce. The solution is to make a workaround
to prevent crashes, while investigating deeply.
> Fix npe in well known config

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
Related to https://github.com/telenordigital/connect-android-sdk/issues/166
> Fix SDK button crashes if it's in "invisible" or "gone" state in Android 5

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ui/ConnectButton.java
- connect/src/com/telenor/connect/ui/ConnectCustomTabLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectTextView.java
- connect/src/com/telenor/connect/ui/ConnectWebViewLoginButton.java
We expect SDK users to have a single entry point to the SDK
and we provide additional fallback options in case if that entry
point fails. Before it was possible to use fallback options directly,
that was allowing the usage of some bad practises. Now this option
will be disabled.
**This is a breaking change.**
> Remove option to use fallback components directly

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/headerenrichment/HeLogic.java
Now SDK is doing HE request each time when there is a network switch. That results in massive ---`prepare` and `inject` traffic towards Header Enrichment. 
This is a temporary fix for the issue, that will set the flag `heWasInitialized ` to true whenever HE prepare-inject was initialised.
Proper fix is scheduled to be done in future. It should include rewrite of network handling logic and solving threading issue while reading results from HE.
> Add temporary fix for HE traffic
