- README.md
- connect/src/com/telenor/connect/id/Claims.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/utils/ClaimsParameterFormatter.java
- connect/tests/src/test/java/com/telenor/connect/id/ClaimsTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ClaimsParameterFormatterTest.java
> Add setClaims to ConnectLoginButton

- connect/src/com/telenor/connect/ConnectNotSignedInException.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/id/ConnectAPI.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/id/UserInfo.java
- connect/tests/src/test/java/com/telenor/connect/id/ConnectIdServiceTest.java
Closes #4.
Implements getUserInfo, for `/oauth/userinfo` endpoint. http://docs.telenordigital.com/apis/connect/id/authentication.html#authorization-server-user-information
> Add getUserInfo

- README.md
- connect-id-example/build.gradle
- connect-id-example/src/main/java/com/telenor/connect/connectidexample/SignedInActivity.java
- connect-id-example/src/main/res/layout/activity_signed_in.xml
- connect-payment-example/build.gradle
- connect/build.gradle
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/ui/ConnectActivity.java
- connect/src/com/telenor/connect/ui/ConnectWebFragment.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- connect/tests/build.gradle
- payment-processor-example/build.gradle
* As a developer I want to easily add claims to the authentication request, so that I later can access the users details #1.
* As a developer I want to access information about the logged in user (i.e. /oauth/userinfo), so that I can access id, email, and phone number #4.
* As a developer I want to easily add claims to the authentication request, so that I later can access the users details #9.
* Added example for setting the UI locale.
* Now displaying the WebView on the `/heidetect` page 300 ms after it starts loading, even if it's not finished loading. #13.
> Development into master

- README.md
- connect/build.gradle
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/id/ActivityFinisherConnectCallback.java
- connect/src/com/telenor/connect/id/Claims.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/id/ConnectTokens.java
- connect/src/com/telenor/connect/id/IdToken.java
- connect/src/com/telenor/connect/utils/ClaimsParameterFormatter.java
- connect/tests/src/test/java/com/telenor/connect/id/ClaimsTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ClaimsParameterFormatterTest.java
* Allow access to ID token fields
* Update IdToken toString with new fields
* Change order of statements in IdToken
* Extract constants in IdToken
* Clearify readme on getting user info
* Correct Claim values
> Give access to ID token fields (#28)

- connect-payment-example/src/main/java/com/telenor/connect/connectpaymentexample/CartActivity.java
- connect/build.gradle
- connect/src/com/telenor/connect/ConnectRefreshTokenMissingException.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/id/AccessTokenCallback.java
- connect/src/com/telenor/connect/id/ConnectAPI.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/id/ConnectTokens.java
- connect/src/com/telenor/connect/id/ConnectTokensTO.java
- connect/src/com/telenor/connect/id/IdToken.java
- connect/src/com/telenor/connect/id/ParseTokenCallback.java
- connect/src/com/telenor/connect/id/TokenStore.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- connect/src/com/telenor/connect/utils/Validator.java
- connect/tests/src/test/java/com/telenor/connect/id/ConnectIdServiceTest.java
- connect/tests/src/test/java/com/telenor/connect/id/ConnectTokensTOStateTrackerTest.java
- connect/tests/src/test/java/com/telenor/connect/id/ParseTokenCallbackTest.java
- connect/tests/src/test/java/com/telenor/connect/ui/ConnectWebViewClientTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ValidatorTest.java
* AccessTokenCallback added. This is callback that gives you an Access Token as a string or an error.
* There are now `ConnectTokens` and `ConnectTokensTO`. The latter is the transfer object. The first can now tell you if the Access Token is expired or not.
> Add getValidAccessToken method to ConnectSdk

- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
Will avoid js console errors of type:
Uncaught TypeError: Cannot read property 'innerHTML' of null
> Check that android-instructions are present

- connect/build.gradle
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ConnectSdkProfile.java
- connect/src/com/telenor/connect/SdkProfile.java
- connect/src/com/telenor/connect/utils/ConnectUrlHelper.java
- connect/src/com/telenor/connect/utils/RestHelper.java
- connect/src/com/telenor/mobileconnect/MobileConnectSdkProfile.java
- connect/src/com/telenor/mobileconnect/operatordiscovery/OperatorDiscoveryAPI.java
This will fix a bug with http2 not working, most notably for the getUserInfo method.
> Upgrade okhttp

- connect-id-example/build.gradle
- connect/src/com/telenor/connect/utils/RestHelper.java
"The issue has just been marked as fixed for the Android Studio Gradle
Version 3.0. There you can just use implementation project(path:
':library') and it'll select the correct configuration automatically."
https://stackoverflow.com/a/29163361
Change-Id: Icd3d85fe35538a83f5a02b3c3a4e8f5b06de9ecf
Jira: IDLIVE-5
> Resolve #98, do not log tokens in release builds

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
https://github.com/telenordigital/connect-android-sdk/pull/69 "Fix the
hotspot issue in the Android SDK" was on the code path only for
WebViews. Add it to the Chrome Custom Tabs too.
> Apply hot spot check when using Chrome Custom Tabs

- connect/src/com/telenor/connect/ConnectSdk.java
> Fix null pointer exception on well known config

- build.gradle
- connect-id-example/build.gradle
- connect/build.gradle
- connect/tests/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobileconnect-example/build.gradle
References: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#new_configurations
https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa
> Update gradle and change deprecated compile to implementation

- connect/src/com/telenor/connect/utils/CustomTabsHelper.java
https://github.com/telenordigital/connect-android-sdk/issues/133
> Workaround for chromeTabs for apps using Jetifier

- connect/src/com/telenor/connect/ui/AuthenticationButton.java
- connect/src/com/telenor/connect/ui/ConnectCustomTabLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectWebViewLoginButton.java
> Add getOnClickListener to AuthenticationButton

- connect/src/com/telenor/connect/ui/ConnectActivity.java
> Use iterator to remove item

- connect-id-example/src/main/AndroidManifest.xml
- connect/res/layout/com_telenor_connect_fragment_enable_mobile_data.xml
- connect/src/com/telenor/connect/AnalyticsAPI.java
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/headerenrichment/DismissDialogCallback.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/ui/TurnOnMobileDataDialogFragment.java
- connect/src/com/telenor/connect/utils/TurnOnMobileDataAnalytics.java
- connect/src/com/telenor/connect/utils/TurnOnMobileDataDialogAnalytics.java
To make the difference between what the feature does and whether or not
it is enabled more clear.
> Rename EnableMobileData -> TurnOnMobileData

- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/ui/ConnectActivity.java
Details: https://github.com/telenordigital/connect-android-sdk/issues/168
> Fix possible NPE when the received object is null

- connect-id-example/src/main/java/com/telenor/connect/connectidexample/SignInActivity.java
- connect/build.gradle
- connect/res/layout/com_telenor_connect_fragment_turn_on_mobile_data.xml
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/headerenrichment/GetHeaderEnrichmentGifTask.java
- connect/src/com/telenor/connect/headerenrichment/HeLogic.java
- connect/src/com/telenor/connect/headerenrichment/MobileDataFetcher.java
- connect/src/com/telenor/connect/id/ConnectTokens.java
- connect/src/com/telenor/connect/id/ConnectTokensStateTracker.java
- connect/src/com/telenor/connect/sms/SmsCursorUtil.java
- connect/src/com/telenor/connect/sms/SmsRetrieverUtil.java
- connect/src/com/telenor/connect/ui/ConnectActivity.java
- connect/src/com/telenor/connect/ui/ConnectCustomTabLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
- connect/src/com/telenor/connect/ui/ConnectWebFragment.java
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- connect/src/com/telenor/connect/ui/ConnectWebViewLoginButton.java
- connect/src/com/telenor/connect/ui/TurnOnMobileDataDialogFragment.java
- connect/src/com/telenor/connect/utils/ClaimsParameterFormatter.java
- connect/src/com/telenor/connect/utils/ConnectUtils.java
- connect/src/com/telenor/connect/utils/HeadersDateUtil.java
- connect/tests/build.gradle
- connect/tests/src/test/java/com/telenor/connect/id/ConnectTokensTOStateTrackerTest.java
- connect/tests/src/test/java/com/telenor/connect/sms/HtmlToAndroidInstructionsInterfaceTest.java
- connect/tests/src/test/java/com/telenor/connect/sms/SmsPinParseUtilTest.java
- connect/tests/src/test/java/com/telenor/connect/ui/ConnectWebViewClientTest.java
- connect/tests/src/test/java/com/telenor/connect/utils/ConnectUtilsTest.java
- gradle.properties
Includes also upgrading example app and test to work with androidx
> Move Android dependencies from support library to androidx

- connect-id-example/src/main/java/com/telenor/connect/connectidexample/ExampleApplication.java
- connect/build.gradle
- connect/res/layout/com_telenor_connect_about.xml
- connect/res/values/strings.xml
- connect/src/com/telenor/connect/id/IdProvider.java
- connect/src/com/telenor/connect/ui/ConnectAboutTextView.java
- Add support for GP ID
- Update dependencies
- Update staging environments
> Add support for GP ID

- connect/res/values-bg-rBG/strings.xml
- connect/res/values-bn-rBD/strings.xml
- connect/res/values-da-rDK/strings.xml
- connect/res/values-hu-rHU/strings.xml
- connect/res/values-in-rID/strings.xml
- connect/res/values-me-rME/strings.xml
- connect/res/values-ms-rMY/strings.xml
- connect/res/values-nb-rNO/strings.xml
- connect/res/values-sr-rCS/strings.xml
- connect/res/values-sv-rSE/strings.xml
- connect/res/values-th-rTH/strings.xml
- connect/res/values-ur-rPK/strings.xml
- connect/res/values-zh-rCN/strings.xml
Adding default language as English to avoid issues when Android fails to roll back to default automatically
> Upgrade default translations for another languages

- connect-id-example/src/main/java/com/telenor/connect/connectidexample/SignInActivity.java
- connect-id-example/src/main/res/layout/activity_sign_in.xml
- connect-id-example/src/main/res/values/strings.xml
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/id/IdProvider.java
- connect/src/com/telenor/connect/utils/ConnectUrlHelper.java
Add the option to call a method in sdk to open
"Manage {brand name}" page properly inside of
Chrome Custom Tabs or default browser instead.
> [android sdk] Add manage {brand name} link

- connect/build.gradle
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/headerenrichment/HeFlowDecider.java
- connect/src/com/telenor/connect/ui/ConnectWebFragment.java
- connect/src/com/telenor/connect/utils/ConnectUrlHelper.java
- Added extra fraud protection for HE functionality
- Changed the logic and flows for HE
> Fraud protection for he and version bump

- connect/src/com/telenor/connect/ui/ConnectLoginButton.java
> Fix wrong check for mobile network availability

- connect-id-example/src/main/java/com/telenor/connect/connectidexample/ExampleApplication.java
- connect-id-example/src/main/res/values/strings.xml
- connect/build.gradle
- connect/src/com/telenor/connect/ui/ConnectWebViewClient.java
- Update example app to make it possible to target new frontend
- Bump version of SDK
> Update example app and bump version

- connect/build.gradle
- connect/res/layout/com_telenor_connect_activity_layout.xml
- connect/src/com/telenor/connect/ConnectSdk.java
- connect/src/com/telenor/connect/WellKnownConfigStore.java
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/id/ConnectStore.java
- Invalidate config in case of wrong issuer
- Fix a bug with empty activity view
- Bump version
> Invalidate config in case of wrong issuer

- build.gradle
- connect/build.gradle
- connect/src/com/telenor/connect/id/ConnectIdService.java
- connect/src/com/telenor/connect/id/ConnectTokens.java
- connect/src/com/telenor/connect/utils/IdTokenValidator.java
- connect/src/com/telenor/connect/utils/Validator.java
1) Fixed unhandled exception
2) Fixed Android 4 support
3) Version bump
> Fix issues leading to crashes

- connect-id-example/src/main/res/values/strings.xml
- connect/build.gradle
- connect/src/com/telenor/connect/ConnectSdk.java
- Add possibility to use intent uri scheme
- Bump version
> Add possibility to use intent uri scheme
